import type { ComponentType } from 'react'

type PageLoader = () => Promise<{ default: ComponentType }>

export const loaders: Record<string, PageLoader> = {
  'admin-dashboard': () => import('@/components/pages/admin/admin-dashboard-page').then(m => ({ default: m.AdminDashboardPage })),
  'admin-analytics': () => import('@/components/pages/admin/admin-analytics-page').then(m => ({ default: m.AdminAnalyticsPage })),
  'admin-revenue-analytics': () => import('@/components/pages/admin/admin-revenue-analytics-page').then(m => ({ default: m.AdminRevenueAnalyticsPage })),
  'admin-booking-analytics': () => import('@/components/pages/admin/admin-booking-analytics-page').then(m => ({ default: m.AdminBookingAnalyticsPage })),
  'admin-user-analytics': () => import('@/components/pages/admin/admin-user-analytics-page').then(m => ({ default: m.AdminUserAnalyticsPage })),
  'admin-provider-analytics': () => import('@/components/pages/admin/admin-provider-analytics-page').then(m => ({ default: m.AdminProviderAnalyticsPage })),
  'admin-customers': () => import('@/components/pages/admin/admin-customers-page').then(m => ({ default: m.AdminCustomersPage })),
  'admin-providers': () => import('@/components/pages/admin/admin-providers-page').then(m => ({ default: m.AdminProvidersPage })),
  'admin-admins': () => import('@/components/pages/admin/admin-admins-page').then(m => ({ default: m.AdminAdminsPage })),
  'admin-roles': () => import('@/components/pages/admin/admin-roles-page').then(m => ({ default: m.AdminRolesPage })),
  'admin-bookings': () => import('@/components/pages/admin/admin-bookings-page').then(m => ({ default: m.AdminBookingsPage })),
  'admin-booking-detail': () => import('@/components/pages/admin/admin-booking-detail-page').then(m => ({ default: m.AdminBookingDetailPage })),
  'admin-categories': () => import('@/components/pages/admin/admin-categories-page').then(m => ({ default: m.AdminCategoriesPage })),
  'admin-coupons': () => import('@/components/pages/admin/admin-coupons-page').then(m => ({ default: m.AdminCouponsPage })),
  'admin-wallets': () => import('@/components/pages/admin/admin-wallets-page').then(m => ({ default: m.AdminWalletsPage })),
  'admin-payments': () => import('@/components/pages/admin/admin-payments-page').then(m => ({ default: m.AdminPaymentsPage })),
  'admin-refunds': () => import('@/components/pages/admin/admin-refunds-page').then(m => ({ default: m.AdminRefundsPage })),
  'admin-amc': () => import('@/components/pages/admin/admin-amc-page').then(m => ({ default: m.AdminAmcPage })),
  'admin-referrals': () => import('@/components/pages/admin/admin-referrals-page').then(m => ({ default: m.AdminReferralsPage })),
  'admin-notifications': () => import('@/components/pages/admin/admin-notifications-page').then(m => ({ default: m.AdminNotificationsPage })),
  'admin-reviews': () => import('@/components/pages/admin/admin-reviews-page').then(m => ({ default: m.AdminReviewsPage })),
  'admin-reports': () => import('@/components/pages/admin/admin-reports-page').then(m => ({ default: m.AdminReportsPage })),
  'admin-fraud': () => import('@/components/pages/admin/admin-fraud-page').then(m => ({ default: m.AdminFraudPage })),
  'admin-support': () => import('@/components/pages/admin/admin-support-page').then(m => ({ default: m.AdminSupportPage })),
  'admin-chat-monitoring': () => import('@/components/pages/admin/admin-chat-monitoring-page').then(m => ({ default: m.AdminChatMonitoringPage })),
  'admin-cms': () => import('@/components/pages/admin/admin-cms-page').then(m => ({ default: m.AdminCmsPage })),
  'admin-seo': () => import('@/components/pages/admin/admin-seo-page').then(m => ({ default: m.AdminSeoPage })),
  'admin-system-settings': () => import('@/components/pages/admin/admin-system-settings-page').then(m => ({ default: m.AdminSystemSettingsPage })),
  'admin-api-settings': () => import('@/components/pages/admin/admin-api-settings-page').then(m => ({ default: m.AdminApiSettingsPage })),
  'admin-email-templates': () => import('@/components/pages/admin/admin-email-templates-page').then(m => ({ default: m.AdminEmailTemplatesPage })),
  'admin-sms-templates': () => import('@/components/pages/admin/admin-sms-templates-page').then(m => ({ default: m.AdminSmsTemplatesPage })),
  'admin-push-notifications': () => import('@/components/pages/admin/admin-push-notifications-page').then(m => ({ default: m.AdminPushNotificationsPage })),
  'admin-audit-logs': () => import('@/components/pages/admin/admin-audit-logs-page').then(m => ({ default: m.AdminAuditLogsPage })),
  'admin-security': () => import('@/components/pages/admin/admin-security-page').then(m => ({ default: m.AdminSecurityPage })),
  'admin-backup': () => import('@/components/pages/admin/admin-backup-page').then(m => ({ default: m.AdminBackupPage })),
  'admin-feature-flags': () => import('@/components/pages/admin/admin-feature-flags-page').then(m => ({ default: m.AdminFeatureFlagsPage })),
  'admin-profile': () => import('@/components/pages/admin/admin-profile-page').then(m => ({ default: m.AdminProfilePage })),
}
